### ISSUE TITLE
linux get -u failed #go version go1.17.10 uname -a Linux kali 5.15.0-kali3-amd64

### ISSUE THREAD

**Issue by passerbyo** [keygen-sh/keygen-go#2]
─# go get -u "github.com/keygen-sh/keygen-go"   

# cd /root/go/GOCODE/src/golang.org/x/sys; git pull --ff-only
From https://go.googlesource.com/sys
   bc2c85a..c0bba94  master     -> origin/master
 * [new branch]      internal-branch.go1.19-vendor -> origin/internal-branch.go1.19-vendor
error: Your local changes to the following files would be overwritten by merge:
        cpu/cpu_gccgo_x86.c
        unix/asm_linux_loong64.s
        unix/errors_freebsd_386.go
        unix/errors_freebsd_amd64.go
        unix/errors_freebsd_arm.go
        unix/errors_freebsd_arm64.go
        unix/linux/Dockerfile
        unix/linux/types.go
        unix/mksysnum.go
        unix/syscall_aix.go
        unix/syscall_bsd.go
        unix/syscall_darwin.go
        unix/syscall_freebsd.go
        unix/syscall_freebsd_386.go
        unix/syscall_freebsd_amd64.go
        unix/syscall_freebsd_arm.go
        unix/syscall_freebsd_arm64.go
        unix/syscall_illumos.go
        unix/syscall_linux.go
        unix/syscall_linux_loong64.go
        unix/syscall_linux_riscv64.go
        unix/syscall_openbsd_mips64.go
        unix/syscall_solaris.go
        unix/syscall_unix.go
        unix/syscall_unix_test.go
        unix/syscall_zos_test.go
        unix/types_darwin.go
        unix/types_freebsd.go
        unix/types_solaris.go
        unix/zerrors_freebsd_386.go
        unix/zerrors_freebsd_amd64.go
        unix/zerrors_freebsd_arm.go
        unix/zerrors_freebsd_arm64.go
        unix/zerrors_linux.go
        unix/zerrors_linux_386.go
        unix/zerrors_linux_amd64.go
        unix/zerrors_linux_arm.go
        unix/zerrors_linux_arm64.go
        unix/zerrors_linux_loong64.go
        unix/zerrors_linux_mips.go
        unix/zerrors_linux_mips64.go
        unix/zerrors_linux_mips64le.go
        unix/zerrors_linux_mipsle.go
        unix/zerrors_linux_ppc.go
        unix/zerrors_linux_ppc64.go
        unix/zerrors_linux_ppc64le.go
        unix/zerrors_linux_riscv64.go
        unix/zerrors_linux_s390x.go
        unix/zerrors_linux_sparc64.go
        unix/zsyscall_freebsd_386.go
        unix/zsyscall_freebsd_amd64.go
        unix/zsyscall_freebsd_arm.go
        unix/zsyscall_freebsd_arm64.go
        unix/zsyscall_linux_loong64.go
        unix/zsyscall_linux_riscv64.go
        unix/zsyscall_solaris_amd64.go
        unix/zsysnum_freebsd_386.go
        unix/zsysnum_freebsd_amd64.go
        unix/zsysnum_freebsd_arm.go
        unix/zsysnum_freebsd_arm64.go
        unix/zsysnum_linux_loong64.go
        unix/zsysnum_linux_riscv64.go
        unix/ztypes_darwin_amd64.go
        unix/ztypes_darwin_arm64.go
        unix/ztypes_freebsd_386.go
        unix/ztypes_freebsd_amd64.go
        unix/ztypes_freebsd_arm.go
        unix/ztypes_freebsd_arm64.go
        unix/ztypes_linux.go
        unix/ztypes_linux_386.go
        unix/ztypes_linux_amd64.go
        unix/ztypes_linux_arm.go
        unix/ztypes_linux_arm64.go
        unix/ztypes_linux_loong64.go
        unix/ztypes_linux_mips.go
        unix/ztypes_linux_mips64.go
        unix/ztypes_linux_mips64le.go
        unix/ztypes_linux_mipsle.go
        unix/ztypes_linux_ppc.go
        unix/ztypes_linux_ppc64.go
        unix/ztypes_linux_ppc64le.go
        unix/ztypes_linux_riscv64.go
        unix/ztypes_linux_s390x.go
        unix/ztypes_linux_sparc64.go
        unix/ztypes_solaris_amd64.go
        windows/syscall_windows.go
        windows/types_windows.go
        windows/zsyscall_windows.go
Please commit your changes or stash them before you merge.
Aborting
package golang.org/x/sys/cpu: exit status 1
# cd /root/go/GOCODE/src/golang.org/x/crypto; git pull --ff-only
From https://go.googlesource.com/crypto
   7b82a4e..0559593  master     -> origin/master
 * [new branch]      internal-branch.go1.19-vendor -> origin/internal-branch.go1.19-vendor
error: Your local changes to the following files would be overwritten by merge:
        acme/acme.go
        acme/autocert/cache.go
        acme/autocert/internal/acmetest/ca.go
        acme/jws.go
        acme/jws_test.go
        acme/rfc8555.go
        acme/rfc8555_test.go

**Comment by ezekg** [comment]
What's the actual issue here? I need more information.

**Comment by ezekg** [comment]
Looks like some sort of Go environment issue. I don't see anything related to this package.

**Comment by ezekg** [comment]
Something isn't right with your Go env. Nothing in that stack trace indicates an issue with keygen-go.

Try manually deleting the package in your Go path and then running`go get` again.

```
rm -r "$GOPATH/src/github.com/keygen-sh/keygen-go"
```

If that doesn't work, try reinstalling Go.
