### ISSUE TITLE
Set package relationship while releasing

### ISSUE THREAD

**Issue by kratman** [keygen-sh/keygen-go#22]
Maybe I missed it in the documentation, but when I do a release with the keygen cli I have to manually set this field:
![image](https://github.com/user-attachments/assets/2c3a11cd-442c-483b-889c-3247fad0816f)

I make the release with the following commands:
```
          export KEYGEN_ACCOUNT_ID=...
          export KEYGEN_PRODUCT_ID=...
          export KEYGEN_PRODUCT_TOKEN=...

          keygen new --version ${RELEASE_VERSION}
          keygen upload ./${WHEEL_NAME} --release ${RELEASE_VERSION}
          keygen publish --release ${RELEASE_VERSION}
```

Is there a method for setting the package relationship with the CLI that I am missing? I would like to fully automate my release workflow, but right now I still need to go set that relationship in the dashboard.

From the docs it looks like I could probably set the relationship with the API, but I would prefer to stick to just the CLI if I can.

**Comment by ezekg** [comment]
You can use the `--package` flag when creating a new release and uploading artifacts.

**Comment by kratman** [comment]
Thanks, I will update my workflow

**Comment by ezekg** [comment]
np!
