### ISSUE TITLE
Clarification about the SDK

### ISSUE THREAD

**Issue by Munsio** [keygen-sh/keygen-go#25]
Hi,

Sorry if this sound a little dumb but I couldn't find any indication if this package is getting any treatment regarding other API use cases like creating a license/user etc.

Or will there be an official API Client for such things in the future? And if not do you accept PRs on this SDK expanding the feature set for User actions like this?

Edit: The slice response was a mistake on my end.

~~Regardless of the question above I also found a "bug" within the API when retrieving a User.~~

~~According to the Documentation https://keygen.sh/docs/api/users/#users-retrieve you can either use the ID or the E-Mail address for fetching. Also E-Mail addresses are unique within an account.~~

~~Unfortunately when trying to use the E-Mail address the API is returning a slice with 1 User, so you can't use both within the same go method without checking the input parameter.~~

**Comment by ezekg** [comment]
Not dumb at all. I'd love to eventually support more API operations. The SDK was initially an exploration into what a 'reference' client-side API would look like that others could use to implement [other](https://github.com/ahonn/keygen-rs) [clients](https://github.com/JZuerlein/KeyGen-sh.Client). But we already have [webhook verification](https://github.com/keygen-sh/keygen-go/blob/86076085a51417604308080285cd6cc40447f6e8/webhook.go#L26) in the SDK, which is a server-side function, so I'm totally open to PRs introducing additional actions such as license and user creation.

The full API's surface area is really big, so I probably won't get to implementing everything in the API anytime soon, unless we move to a generated SDK based on e.g. an OpenAPI spec. But open to PRs to introduce certain things.

The way I've extended the SDK myself is by defining a `keygenext` package. For example, [the CLI extends the SDK](https://github.com/keygen-sh/keygen-cli/tree/master/internal/keygenext) to add release creation and publishing, artifact uploading, among some other things.
