### ISSUE TITLE
../github.com/oasisprotocol/curve25519-voi/internal/toolchain/constraints.go:48:6: undefined: __SOFTWARE_REQUIRES_GO_VERSION_1_18__

### ISSUE THREAD

**Issue by gouserdev** [keygen-sh/keygen-go#5]
package main

import (
	"fmt"

	"github.com/denisbrodbeck/machineid"
	"github.com/keygen-sh/keygen-go"
)

func main() {
	keygen.Account = "YOUR_KEYGEN_ACCOUNT_ID"
	keygen.Product = "YOUR_KEYGEN_PRODUCT_ID"
	keygen.LicenseKey = "key/..."

	fingerprint, err := machineid.ProtectedID(keygen.Product)
	if err != nil {
		panic(err)
	}

	// Validate the license for the current fingerprint
	license, err := keygen.Validate(fingerprint)
	switch {
	case err == keygen.ErrLicenseNotActivated:
		// Activate the current fingerprint
		machine, err := license.Activate(fingerprint)
		switch {
		case err == keygen.ErrMachineLimitExceeded:
			panic("machine limit has been exceeded!")
		case err != nil:
			panic("machine activation failed!")
		}
	case err == keygen.ErrLicenseExpired:
		panic("license is expired!")
	case err != nil:
		panic("license is invalid!")
	}

	fmt.Println("License is activated!")
}

**Comment by ezekg** [comment]
That package requires Go v1.18, as stated by the error message. I recommend upgrading to Go v1.18.

Use with v1.17 at your own risk.
